USE [master]
GO

/****** Object:  Database [company sales]    Script Date: 6/3/2022 3:04:25 PM ******/
CREATE DATABASE [company sales]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'company sales', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\company sales.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'company sales_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\company sales_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [company sales].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [company sales] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [company sales] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [company sales] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [company sales] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [company sales] SET ARITHABORT OFF 
GO

ALTER DATABASE [company sales] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [company sales] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [company sales] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [company sales] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [company sales] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [company sales] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [company sales] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [company sales] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [company sales] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [company sales] SET  DISABLE_BROKER 
GO

ALTER DATABASE [company sales] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [company sales] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [company sales] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [company sales] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [company sales] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [company sales] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [company sales] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [company sales] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [company sales] SET  MULTI_USER 
GO

ALTER DATABASE [company sales] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [company sales] SET DB_CHAINING OFF 
GO

ALTER DATABASE [company sales] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [company sales] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [company sales] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [company sales] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [company sales] SET QUERY_STORE = OFF
GO

ALTER DATABASE [company sales] SET  READ_WRITE 
GO

